name: Split Fonts to new Branch

on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  split: 
    runs-on: ubuntu-latest
    steps:
      - name: Script Version
        run: |
          echo "::group::Script Versioning"
          $scriptVersion = "1.0.2"
          echo "Build Script Version: $scriptVersion"
          echo "::endgroup::"
        shell: pwsh   
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          clean: true
      - uses: actions/setup-node@v3
      - name: upm subtree split
        if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
        run: |
          $packageDir = Get-Item -Path "Fonts" | Select-Object -ExpandProperty FullName
          $packageDir = $packageDir.replace('${{ github.workspace }}/','')
          Write-Host "::group:: $packageDir subtree split"
          git subtree split --prefix="$packageDir" -b fonts
          Write-Host "::endgroup::"
          git push -f origin fonts
        working-directory: ${{ github.workspace }}
        shell: pwsh      